name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Deploy Project to Vercel
      run: pnpm vercel deploy --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
