name: CI

on:
  push:
    branches: [master, feat/**]
  pull_request:
    branches: [master]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Lint / Typecheck / Test / Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install pnpm globally
        run: npm i -g pnpm@10

      - name: Verify pnpm
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CI pipeline
        run: pnpm run ci

  spec-validator:
    name: Spec Validator
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Make scripts executable
        run: |
          chmod +x spec/scripts/*.sh scripts/*.sh || true
      - name: Sync templates if needed
        run: |
          ./scripts/sync-templates.sh || true
      - name: Validate spec structure
        run: |
          ./spec/scripts/validate-spec.sh
      - name: OpenAPI lint (optional)
        run: |
          npx -y @redocly/openapi-cli@latest lint spec/specs/003-my-feature/contracts/booking.openapi.yml || true
      - name: Generate API types (optional)
        run: |
          npx -y openapi-typescript@latest spec/specs/003-my-feature/contracts/booking.openapi.yml --output src/types/generated/booking-api.ts || true
